# /// script
# dependencies = [
#   "django-bolt[nanodjango]",
# ]
# ///
"""
Minimal django-bolt + nanodjango single-file example.

Run via nanodjango's CLI:
    nanodjango manage examples/nanodjango/helloworld.py runbolt --port 8000

or

run with automatic dependency downloads and virtenv creation:
    uv run examples/nanodjango/helloworld.py runbolt --port 8000
"""

from __future__ import annotations

import asyncio
import sys
from collections.abc import AsyncIterable
from html import escape
from pathlib import Path

import msgspec
from nanodjango import Django

from django_bolt import WebSocket, WebSocketDisconnect
from django_bolt.nanodjango import BoltAPI
from django_bolt.responses import EventSourceResponse

app = Django()
bolt = BoltAPI()


@app.route("/")
def home(request):
    # sys.argv[0] (not __file__) so this survives ``nanodjango convert`` —
    # the AST resolver can't trace __file__ but treats sys as a known import.
    try:
        source = Path(sys.argv[0]).read_text()
    except OSError:
        source = "(source unavailable)"
    return f"""<title>helloworld: django-bolt+nanodjango</title>
    <h1>Hello, single file apps with Django-Bolt and nanodjango</h1>
    This page is a django view, served by the bolt/Actix server. The links below introduce bolt's API calls which return json responses.<br/>
<nav aria-label="Api Navigation">
  <ul>
    <li><a href="/api/hello">/api/hello</a> - say hello</li>
    <li><a href="/api/greet?name=World">/api/greet?name=World</a> - return greeting with name=World</li>
    <li><a href="/api/greeting?name=ada">/api/greeting?name=ada</a> - msgspec.Struct response model</li>
    <li><a href="/api/stream">/api/stream</a> - SSE stream, 5 messages over 5 seconds</li>
    <li><code>ws://&lt;host&gt;/ws/echo</code> - WebSocket echo (try it below)</li>
  </ul>
</nav>

<section aria-label="WebSocket tester">
  <h2>WebSocket echo</h2>
  <input id="ws-input" placeholder="type and press Enter" autocomplete="off"/>
  <pre id="ws-log" style="background:#f4f4f4;padding:.5em;min-height:4em"></pre>
  <script>
    const log = document.getElementById('ws-log');
    const input = document.getElementById('ws-input');
    const proto = location.protocol === 'https:' ? 'wss:' : 'ws:';
    const ws = new WebSocket(`${{proto}}//${{location.host}}/ws/echo`);
    ws.onmessage = (e) => log.textContent += '<- ' + e.data + '\\n';
    ws.onopen = () => log.textContent += '(connected)\\n';
    ws.onclose = () => log.textContent += '(closed)\\n';
    input.addEventListener('keydown', (e) => {{
      if (e.key === 'Enter' && input.value) {{
        ws.send(input.value);
        log.textContent += '-> ' + input.value + '\\n';
        input.value = '';
      }}
    }});
  </script>
</section>

    <p>Check out the autogenerated <a href="/docs/">API docs</a>.</p>

    <details>
    <summary>Source Code</summary>
    <pre>{escape(source)}</pre></details>
    """


@bolt.get("/api/hello")
async def hello(request):
    return {"message": "hello from bolt"}


@bolt.get("/api/greet")
async def greet(name: str):
    return {"message": f"hello, {name}!"}


class Greeting(msgspec.Struct):
    """Typed response schema. The ``-> Greeting`` annotation below tells
    django-bolt to serialize via msgspec (much faster than json.dumps)
    and to publish the schema in the auto-generated OpenAPI docs."""

    name: str
    excited: bool = False


@bolt.get("/api/greeting")
async def get_greeting(name: str = "world") -> Greeting:
    """Return a Greeting struct — demonstrates response-model serialization.
    Try ``/api/greeting?name=ada`` → ``{"name":"Ada","excited":true}``."""
    return Greeting(name=name.title(), excited=True)


@bolt.get("/api/stream", response_class=EventSourceResponse)
async def stream() -> AsyncIterable[dict]:
    """yield 5 SSE messages, one per second. EventSourceResponse handles
    JSON encoding, SSE framing, and skipping compression."""
    for i in range(5):
        yield {"message": f"message {i}"}
        await asyncio.sleep(1)


@bolt.websocket("/ws/echo")
async def ws_echo(websocket: WebSocket):
    """Accept a WebSocket connection and echo every text message back."""
    await websocket.accept()
    try:
        while True:
            msg = await websocket.receive_text()
            await websocket.send_text(f"echo: {msg}")
    except WebSocketDisconnect:
        pass


# Register catch-all AFTER all bolt routes so they take priority.
# Unmatched requests (like /) are forwarded to Django's ASGI app.
bolt.mount_django(r"/")


if __name__ == "__main__":
    from django.core.management import execute_from_command_line

    execute_from_command_line(sys.argv)
